# Generated by Django 5.0 on 2024-01-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='TTM_table',
        ),
    ]
